server:
  port: 8765

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: araok
          uri: lb://araok
          predicates:
            - Path=/api/limit

management:
  endpoints:
    web:
      exposure:
        include: "*"
