spring:
  data:
    rest:
      base-path: /rest
  datasource:
    url: ${MY_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/araok}
    username: araok
    password: araok
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: ${MY_SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/araok}
    user: araok
    password: araok

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0
      
app:
  count-content-downloads: 1000