spring:
  data:
    rest:
      base-path: /rest
  datasource:
    url: jdbc:postgresql://localhost:5432/araok
    username: araok
    password: araok
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:postgresql://localhost:5432/araok
    user: araok
    password: araok

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0
      
app:
  count-content-downloads: 1000